package:
  name: ruby3.2-zstd-ruby
  version: "2.0.2"
  epoch: 0
  description: Ruby binding for zstd-ruby(Zstandard - Fast real-time compression algorithm)
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - ruby${{vars.rubyMM}}-concurrent-ruby
      - ruby-${{vars.rubyMM}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-${{vars.rubyMM}}
      - ruby-${{vars.rubyMM}}-dev

vars:
  gem: zstd-ruby

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cb4b3f7bdf9f7156446216c4fe9f3006f26529fc
      repository: https://github.com/SpringMT/zstd-ruby
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: SpringMT/zstd-ruby
    strip-prefix: v

test:
  pipeline:
    - runs: ruby -e "require 'zstd-ruby'"

var-transforms:
  - from: ${{package.name}}
    match: ^ruby(\d\.\d+)-.*
    replace: $1
    to: rubyMM
